### ISSUE TITLE
fix ph_diagplot function labels

### ISSUE THREAD

**Issue by MikeJSeo** [hta-pharma/maicplus#133]
![image](https://github.com/user-attachments/assets/0fcaa5a7-a578-4722-bcc7-a4582373530b)

ph_diagplot_unanchored.ex.R
- labels not printing correctly (treatment A and treatment B off the plot)
- same issue for ph_diagplot_anchored.ex.R

**Comment by gravesti** [comment]
Ok, I see this seems to happen because resizing the plot window doesn't fully redraw the plot. I think this is because it is made up of multiple plots and the dimensions are not recalculated to fix the placement of the legend. If you first make the plot window big, then run ph_diagplot() it should look correct. 

Not sure if we can fix this easily...

**Comment by MikeJSeo** [comment]
Ah it seems to work if I resize the plot window! Didn't know! Thanks for checking @gravesti 
I'll close the issue
