### ISSUE TITLE
Bootstrapping in unanchored MAIC

### ISSUE THREAD

**Issue by conorchand** [hta-pharma/maicplus#182]
Hi,
I would recommend revisiting the approach to bootstrapping in the unanchored setting.  The current implementation neglects to account for all sources of uncertainty by limiting the resampling procedure to the index trial population, which implicitly assumes that there is no uncertainty in the comparator's estimated mean outcome. 
Thank you!
Conor

**Comment by MikeJSeo** [comment]
Hi Conor (@conorchand),

Thanks for bringing this up! Yes, we knew about this for quite some time. We implemented bootstrap for unanchored for completeness and also because we wanted to write a simulation paper on this. But, I guess you guys did the work for us. I haven't read the paper in close detail, but what we also recommend is just using sandwich estimators over (partial) bootstrap for unanchored comparison.
@gravesti @hoppanda feel free to add any comments on this

Best,
Michael

**Comment by MikeJSeo** [comment]
Hi again @conorchand,
 
I had some time to read over your paper and I found it super helpful and insightful. Thank you!
I had two initial questions/comments.

1) It is amazing how simply scaling to ESS led to much better improvements! Up till now, we were mostly interested in scaling the weights to N so as the number at risk table in the KM plot makes better sense (at least for time = 0). However, one concern I have is that the HTA bodies wouldn't like confidence intervals that are not based on sandwich estimator nor bootstrap. Could scaling the weights to ESS and also applying sandwich estimator (i.e. for unanchored) be an optimal approach in your opinion?

2) Just a quick comment on what you call "bootstrap". I think we have never considered implementing this type of bootstrap as sampling comparator trial (outcome) leads to changes to the aggregate covariates summaries. Since we do not have full covariate information for the patients in the comparator trial, this approach would bring variance estimates closer to the truth, but at the cost of biasing the treatment effect. Any thoughts on this?

Best,
Michael

**Comment by MikeJSeo** [comment]
Hi Conor (@conorchand),

I had some time to read over your paper and I found it super helpful and insightful. Thank you!
I had two initial questions/comments if I may ask you.

- It is amazing how simply scaling to ESS led to much better improvements! Up till now, we were mostly interested in scaling the weights to N so as the number at risk table in the KM plot makes better sense (at least for time = 0). However, one concern I have is that the HTA bodies wouldn't like confidence intervals that are not based on sandwich estimator nor bootstrap. Could scaling the weights to ESS and also applying sandwich estimator (i.e. for unanchored) be the optimal approach in your opinion?

- Just a quick comment on what you call "bootstrap". I think we have never considered implementing this type of bootstrap as sampling comparator trial (outcome) leads to changes to the aggregate covariates summaries. Since we do not have full covariate information for the patients in the comparator trial, this approach would bring variance estimates closer to the truth, but at the cost of biasing the treatment effect. Any thoughts on this?

Best,
Michael

**Comment by conorchand** [comment]
Hi Michael,

Many thanks for your feedback and thoughtful questions. 
Below are my responses to your initial comments and queries. Please let me know if anything requires further clarification.
 
1) I agree that it makes sense to scale the weights to sum to the ESS to construct the number at risk table for KM plots. I’m not sure how it’s handled in maicplus, but I would recommend rescaling at the arm-level as opposed to rescaling based on an overall ESS. Due to non-linearity, the two approaches may not coincide. 

It’s true that conventional estimators (with ESS-scaled weights) are not recommended under current guidelines, and it’s uncertain how this approach would be received by HTAs. 

Sandwich estimators are invariant to the scaling of the weights (i.e., variance estimates would be the same). To verify this, we did actually test sandwich estimators with ESS-scaled weights in the simulation (R programs are available in the Supplement). 

2) Bootstrapping in unanchored MAICs presents several challenges, primarily due to the limited data available for the comparator study. As you highlighted, the true relationship between covariates and outcomes in the comparator study is unknown, making it impossible to jointly sample covariates and outcomes. Theoretically, the aggregate covariate statistics should also vary across each bootstrap resample. However, in this case, the “bootstrap” was limited to sampling outcomes independently of covariates for the comparator -- assuming fixed covariate targets. 

Alternative approaches could circumvent this potential issue. For instance, the paper also explored a “hybrid bootstrap” where only patients from the index trial were resampled, and outcomes for the comparator were simulated based on a parametric distribution (defined according to the hypothetically published mean and variance). Similarly, the bootstrap could be used solely to estimate the variance for treatment in the index trial, which could then be combined with the published variance for the comparator. It is worth noting that the “bootstrap” and “hybrid bootstrap” generally led to comparable estimates across the scenarios we tested. 

Regarding your last point, I assume you are referring to the potential for a biased treatment effect estimate if the mean from the bootstrap were used. Alternatively, the point estimate could be based on the MLE (calculated without the use of bootstrapping), with only the uncertainty estimates derived from the bootstrap.  

Best,
Conor

**Comment by MikeJSeo** [comment]
Hi Conor (@conorchand),

Thanks for the detailed response!! 
1c) Didn't know sandwich estimators are invariant to the scaling of the weights. Good to know!
2a) Yes, what I meant by bias in my previous response is this part: that the aggregate covariate statistics should also vary across each bootstrap resample, but we are assuming it as fixed covariate targets. This was mostly why we ruled this approach out of the considerations, although I also personally think this would be a better bootstrap method over the partial bootstrap (which is plainly wrong).

Regardless, I think I would still recommend using the sandwich estimator for unanchored comparison and it looks like luckily in your simulations, sandwich estimators didn't do so poorly compared to other methods (with adequate sample size and overlap). I think rest of our group is out for this year and so I will discuss with them once they get back. Happy holidays! 

Best,
Michael
